### ISSUE TITLE
Question: preferred method of removing cloned repos?

### ISSUE THREAD

**Issue by olets** [agkozak/zcomet#12]
I added a plugin

```shell
# .zshrc

zcomet load <owner>/<repo>
```

and then disabled it

```shell
# .zshrc

# zcomet load owner/repo
```

Is there a zcomet-y way of deleting the cloned repo? Or is `rm -rf $ZCOMET[REPOS_DIR]/<owner>/<repo>` the way to go?

**Comment by agkozak** [comment]
`zcomet` makes a dynamic named directory for each repo, so give

    rm -rf ~[repo]

a try.

**Comment by olets** [comment]
Thanks!

Could be neat to have a `zcomet rm` or similar, but for me it doesn't rise to the importance of opening a feature request.
