### ISSUE TITLE
Loading local plugins

### ISSUE THREAD

**Issue by spainbran** [agkozak/zcomet#2]
Hello,

Just trying this out and had a small question.

How can I load a local plugin not on github:
zcomet load $HOME/plugin/plugin.zsh
zcomet snippet $HOME/plugin/plugin.zsh

Or is this not possible yet?

**Comment by agkozak** [comment]
I am planning on adding local plugins and snippets as features. Let's leave this issue open, and I will try to implement something very soon. And thanks for asking: you're helping me to decide what I should prioritize.

**Comment by agkozak** [comment]
If you try the `local` branch, you’ll see that I’ve added supports for local snippets. You can just say

    zcomet snippet /path/to/my-snippet.zsh

and it will get sourced and added to the snippet list that `zcomet list` outputs. The snippet can be located anywhere, but you might want to avoid keeping it in `~/.zcomet/snippets` (or your equivalent) for now. `zcomet update` tries to re-download everything in that directory.

Local plugins are next on my list.

**Comment by Onfroygmx** [comment]
Hello, 

Same user, different account.
Did a small test and only had one error when testing the update function:

<details>
<summary>Update Command</summary>

`zcomet ~ > zcomet update                                                                                                                                                                                                                                              20:06:49#
zsh-users/zsh-autosuggestions: 
Already up to date.
zsh-users/zsh-history-substring-search: 
Already up to date.
zsh-users/zsh-syntax-highlighting: 
Already up to date.
Could not source snippet ~/.dot/zsh/modules/aliases/aliases.zsh.
Could not source snippet ~/.dot/zsh/modules/history/history.zsh.
Could not source snippet ~/.dot/zsh/modules/colored-man/colored-man.zsh.
Could not source snippet ~/.dot/zsh/modules/dircolor/dircolor.zsh.
Could not source snippet ~/.dot/zsh/modules/completion/completion.zsh.`

</details>


nothing to worry about.
Did some tests you can see the results here:
https://github.com/Onfroygmx/dotbench

Added a branch for zcomet.

**Comment by agkozak** [comment]
I knew I would miss something! All right -- I just added a condition so that `zcomet update` won't try to source any local snippets.

I look forward to reviewing your tests later in the day -- thanks!

**Comment by Onfroygmx** [comment]
It's just a test config to see the basic times and the outputs of the different module managers compared to a basic source commands in .zshrc and manual git clone your plugins (also the complexity to use them).
there is an install.zsh file for the template and I added a times.txt file for the results.

Still planning to do it with others.

**Comment by agkozak** [comment]
@spainbran @Onfroygmx OK, I just added support for local plugins on the `local` branch. Let me know what you think.

**Comment by Onfroygmx** [comment]
All the basics work for me, so this can be closed.

**Comment by agkozak** [comment]
I'm so happy! Thanks so much for your help.
