### ISSUE TITLE
[bug] `zcomet load githubuser/repo@ref` submodule error

### ISSUE THREAD

**Issue by olets** [agkozak/zcomet#21]
## Expected

Submodules are handled succesfully, whether the default branch is loaded

```shell
zcomet user/repo-with-submodule
```

or some other ref is

```shell
zcomet user/repo-with-submodule@ref
```

## Actual

`zcomet load`ing a repo with a submodule works when loading the default branch, but leads to an error.

Where you'd expect the last line of output to be

```
% zcomet load user/repo-with-submodule
# snip
Submodule path '<submodule name>': checked out '<sha>'
%
```

there are additional lines

```shell
% zcomet load <user>/<repo>@<branch>
# snip
Submodule path '<submodule name>': checked out '<sha>'
fatal: not a git repository: ../.git/modules/<submodule name>
fatal: could not reset submodule index
Could not checkout `<branch>'.
%
```

## Steps to reproduce

1. Create a new GitHub repo
2. Add a submodule to default branch, commit, and push
3. `zcomet load <github user>/<github repo>@$(git rev-parse @)`

Here's a demo repo https://github.com/olets/submoduled

It has branches

```
• < main < no-submodule-changes-compared-to-main
         \
           adds-submodule-zcomet
```

- `main` has https://github.com/olets/zsh-abbr as a submodule
- `zcomet load olets/submoduled` should work
- `zcomet load olets/submoduled@no-submodule-changes-compared-to-main` should work but doesn't for me
- `zcomet load olets/submoduled@adds-submodule-zcomet` should work but doesn't for me

## More info

I'm on

- zsh 5.9 (arm-apple-darwin21.3.0)
- OSTYPE darwin21.3.0
- git version 2.47.0
- latest zcomet as of this writing

I haven't looked into how `zcomet load` works. (Resisting for now after getting sucked into many time consuming open source adventures in the last few days heh). Notably this error happens when one git equivalent,

```shell
git clone --recurse-submodules --single-branch --branch <branch> https://github.com/<user>/<repo>
```

succeeds.

**Comment by agkozak** [comment]
Thanks for the admirably detailed report! I'll get back to you.

**Comment by agkozak** [comment]
I can't get any of my systems to produce your error message, but I see that there *is* a bug in `zcomet` related to how Git submodules work. I should have time to address it on Monday. I'll send you a message when I'm ready for you to test the fix, OK?

**Comment by olets** [comment]
Don't rush for my sake - my need was brief. Happy to help test though.

**Comment by agkozak** [comment]
OK, I've produced a patch on the `submodules` branch which should fix your problem. Go ahead and try it, and many thanks.

**Comment by olets** [comment]
Works for me! Thank you!
