### ISSUE TITLE
'load' vs 'compile'

### ISSUE THREAD

**Issue by ahgraber** [agkozak/zcomet#6]
If I add plugins using `zcomet load`, is there any reason to also run `zcomet compile`?  
I believe I understand from the source code that `load` also compiles wordcode for the repository or fileset that is being loaded. 

Thanks for the clarification!

**Comment by agkozak** [comment]
> -- is this order applicable/recommended for zcomet as well?

Try the order they suggest first. Those sort of plugins interfere with each other a good deal, and there's nothing I can do as a plugin manager developer to make them play nice with each other.
