### ISSUE TITLE
Cannot source fast-syntax-highlighting

### ISSUE THREAD

**Issue by mecurc** [agkozak/zcomet#9]
When i login to shell via ssh i got warning: `Cannot source /home/cloud/.zcomet/repos/zdharma-continuum/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh.`

But looks like here no problem with sourcing it because i have syntax highlighting. I also can source it manually without any problems.

My ~/.zshrc
```bash
export LANG="en_US.UTF-8"
export HOMEBREW_PATH="/opt/homebrew/bin"
export N_PREFIX="$HOME/.n"
export PATH="/Applications/Sublime Text.app/Contents/SharedSupport/bin:$N_PREFIX/bin:$HOMEBREW_PATH:$PATH"
export EDITOR="subl -w"

alias has-starship="command -v starship > /dev/null"
if has-starship; then
  eval "$(starship init zsh)"
fi

if [ ! -d ~/.venv ]; then
  python3 -m venv ~/.venv
fi
source ~/.venv/bin/activate

bindkey "\e[1;3D" backward-word
bindkey "\e[1;3C" forward-word

# Custom aliases
alias sqlite="$HOMEBREW_PATH/sqlite3_ext"
alias ssh="kitty +kitten ssh"
alias unsafe_ssh="ssh -o StrictHostKeyChecking=no"
alias tree="nnn"
alias rm_ds_store="find . -type f -name '*.DS_Store' -ls -delete"

cht() { curl "cht.sh/$1"; }

macos_update() {
  zcomet self-update && zcomet update && \
  brew upgrade && brew upgrade --cask && brew cleanup -s && rm -rf "$(brew --cache)" && \
  npm i -g npm@latest && \
  softwareupdate -l
}

# Clone zcomet if necessary
if [[ ! -f ${ZDOTDIR:-${HOME}}/.zcomet/bin/zcomet.zsh ]]; then
  command git clone https://github.com/agkozak/zcomet.git ${ZDOTDIR:-${HOME}}/.zcomet/bin
fi

zstyle '*:*' color 'yes'
zstyle '*:*' case-sensitive 'yes'

source ${ZDOTDIR:-${HOME}}/.zcomet/bin/zcomet.zsh

zcomet load zdharma-continuum/fast-syntax-highlighting
zcomet load zdharma-continuum/history-search-multi-word
zcomet load zsh-users/zsh-autosuggestions

zcomet load --no-submodules prezto
zcomet load prezto modules/utility
zcomet load prezto modules/directory

zcomet compinit
```

Versions:
OS: Linux rocky8 4.18.0-305.25.1.el8_4.x86_64 #1 SMP Tue Nov 2 10:32:37 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
ZSH: zsh 5.5.1 (x86_64-redhat-linux-gnu)

**Comment by agkozak** [comment]
The last line of `fast-syntax-highlighting.plugin.zsh` ends with

    … || zmodload zsh/nearcolor &>/dev/null

and since you’re using Zsh 5.5.1, you don’t have the `nearcolor` module, and so sourcing the script returns `1` — failure. You’ll see that if you type

    source fast-syntax-highlighting.plugin.zsh; echo $?

And yet it does seem to work perfectly, doesn’t it? This should be easy to fix, I think. For now, please edit `fast-syntax-highlighting.plugin.zsh` so that the last line ends with `|| :`. In the morning I’ll look at the source code and approach the `zdharma-continuum` maintainers.

**Comment by agkozak** [comment]
OK, the `zdharma-continuum` maintainers have accepted my patch, so you can go back to using their latest version.
